/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *quit1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *show_radio_id1;
  GtkWidget *about1;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button13;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *button12;
  GtkWidget *table1;
  GtkWidget *artist_entry;
  GtkWidget *song_entry;
  GtkWidget *station_entry;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *category_entry;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *button16;
  GtkWidget *image24;
  GtkWidget *button17;
  GtkWidget *image23;
  GtkWidget *host_status_image;
  GtkWidget *host_ip_entry;
  GtkWidget *image27;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkWidget *vbox7;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist2;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *scrolledwindow4;
  GtkWidget *clist4;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label20;
  GtkWidget *scrolledwindow3;
  GtkWidget *clist3;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label21;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_window_set_title (GTK_WINDOW (window1), _("Ximba Radio"));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem1_menu, "menuitem1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem4_menu, "menuitem4_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  show_radio_id1 = gtk_menu_item_new_with_mnemonic (_("_Show Radio ID"));
  gtk_widget_set_name (show_radio_id1, "show_radio_id1");
  gtk_widget_show (show_radio_id1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), show_radio_id1);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-apply", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button13 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button13"),
                                _("Connect to server."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button13, "button13");
  gtk_widget_show (button13);
  gtk_widget_add_accelerator (button13, "clicked", accel_group,
                              GDK_O, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-cancel", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button3 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button3"),
                                _("Disconnect from server."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-up", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button4"),
                                _("Channel Up."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_U, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-down", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button5"),
                                _("Channel Down."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_widget_add_accelerator (button5, "clicked", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-jump-to", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button6 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button6"),
                                _("Jump to Channel."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button6, "button6");
  gtk_widget_show (button6);
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              GDK_J, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-back", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button7 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button7"),
                                _("Previous Channel."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_widget_add_accelerator (button7, "clicked", accel_group,
                              GDK_B, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button8 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-refresh",
                                "gtk-refresh",
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-yes", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button9 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button9"),
                                _("Mute off."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button9, "button9");
  gtk_widget_show (button9);
  gtk_widget_add_accelerator (button9, "clicked", accel_group,
                              GDK_O, GDK_CONTROL_MASK | GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-no", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button10 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button10"),
                                _("Mute on."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button10, "button10");
  gtk_widget_show (button10);
  gtk_widget_add_accelerator (button10, "clicked", accel_group,
                              GDK_M, GDK_CONTROL_MASK | GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-justify-fill", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button11 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button11"),
                                _("Toggle List Windows."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button11, "button11");
  gtk_widget_show (button11);
  gtk_widget_add_accelerator (button11, "clicked", accel_group,
                              GDK_L, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-preferences", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button12 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button12"),
                                _("Preferences."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button12, "button12");
  gtk_widget_show (button12);

  table1 = gtk_table_new (5, 4, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, FALSE, FALSE, 0);

  artist_entry = gtk_entry_new ();
  gtk_widget_set_name (artist_entry, "artist_entry");
  gtk_widget_show (artist_entry);
  gtk_table_attach (GTK_TABLE (table1), artist_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (artist_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (artist_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (artist_entry), FALSE);

  song_entry = gtk_entry_new ();
  gtk_widget_set_name (song_entry, "song_entry");
  gtk_widget_show (song_entry);
  gtk_table_attach (GTK_TABLE (table1), song_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (song_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (song_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (song_entry), FALSE);

  station_entry = gtk_entry_new ();
  gtk_widget_set_name (station_entry, "station_entry");
  gtk_widget_show (station_entry);
  gtk_table_attach (GTK_TABLE (table1), station_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (station_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (station_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (station_entry), FALSE);

  label3 = gtk_label_new (_("Song:"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 4, 0);

  label4 = gtk_label_new (_("Station"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 4, 0);

  label5 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 4, 0);

  category_entry = gtk_entry_new ();
  gtk_widget_set_name (category_entry, "category_entry");
  gtk_widget_show (category_entry);
  gtk_table_attach (GTK_TABLE (table1), category_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (category_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (category_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (category_entry), FALSE);

  label2 = gtk_label_new (_("Artist:"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 4, 0);

  label1 = gtk_label_new (_("XM Host:"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 4, 0);

  button16 = gtk_button_new ();
  gtk_widget_set_name (button16, "button16");
  gtk_widget_show (button16);
  gtk_table_attach (GTK_TABLE (table1), button16, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button16, _("Add to Favorites"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button16), GTK_RELIEF_NONE);

  image24 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_set_name (image24, "image24");
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (button16), image24);

  button17 = gtk_button_new ();
  gtk_widget_set_name (button17, "button17");
  gtk_widget_show (button17);
  gtk_table_attach (GTK_TABLE (table1), button17, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button17, _("Add to Favorites"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button17), GTK_RELIEF_NONE);

  image23 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_set_name (image23, "image23");
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (button17), image23);

  host_status_image = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (host_status_image, "host_status_image");
  gtk_widget_show (host_status_image);
  gtk_table_attach (GTK_TABLE (table1), host_status_image, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (host_status_image, FALSE);

  host_ip_entry = gtk_entry_new ();
  gtk_widget_set_name (host_ip_entry, "host_ip_entry");
  gtk_widget_show (host_ip_entry);
  gtk_table_attach (GTK_TABLE (table1), host_ip_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (host_ip_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (host_ip_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (host_ip_entry), FALSE);

  image27 = create_pixmap (window1, "banner.xpm");
  gtk_widget_set_name (image27, "image27");
  gtk_widget_show (image27);
  gtk_table_attach (GTK_TABLE (table1), image27, 3, 4, 0, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (image27), 0, 0.5);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, FALSE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook1), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist1 = gtk_clist_new (6);
  gtk_widget_set_name (clist1, "clist1");
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_widget_set_size_request (clist1, 525, 275);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label15 = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  label16 = gtk_label_new (_("Artist"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  label17 = gtk_label_new (_("Song"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label17);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  label18 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label18);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  label19 = gtk_label_new (_("Ch #"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);

  label35 = gtk_label_new (_("Usage"));
  gtk_widget_set_name (label35, "label35");
  gtk_widget_show (label35);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, label35);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_LEFT);

  label34 = gtk_label_new (_("All Stations"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label34);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_LEFT);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox7);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist2 = gtk_clist_new (6);
  gtk_widget_set_name (clist2, "clist2");
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist2);
  gtk_widget_set_size_request (clist2, 525, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  label22 = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_show (label22);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label22);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);

  label23 = gtk_label_new (_("Artist"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_show (label23);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, label23);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  label24 = gtk_label_new (_("Song"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, label24);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  label25 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 3, label25);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);

  label26 = gtk_label_new (_("Ch #"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 4, label26);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_LEFT);

  label27 = gtk_label_new (_("Usage"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 5, label27);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_LEFT);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist4 = gtk_clist_new (6);
  gtk_widget_set_name (clist4, "clist4");
  gtk_widget_show (clist4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), clist4);
  gtk_widget_set_size_request (clist4, 525, 175);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist4));

  label36 = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_show (label36);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 0, label36);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_LEFT);

  label37 = gtk_label_new (_("Artist"));
  gtk_widget_set_name (label37, "label37");
  gtk_widget_show (label37);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 1, label37);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_LEFT);

  label38 = gtk_label_new (_("Song"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_show (label38);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 2, label38);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_LEFT);

  label39 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label39, "label39");
  gtk_widget_show (label39);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 3, label39);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_LEFT);

  label40 = gtk_label_new (_("Ch #"));
  gtk_widget_set_name (label40, "label40");
  gtk_widget_show (label40);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 4, label40);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_LEFT);

  label41 = gtk_label_new (_("Usage"));
  gtk_widget_set_name (label41, "label41");
  gtk_widget_show (label41);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 5, label41);
  gtk_label_set_justify (GTK_LABEL (label41), GTK_JUSTIFY_LEFT);

  label20 = gtk_label_new (_("Favorites"));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label20);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist3 = gtk_clist_new (6);
  gtk_widget_set_name (clist3, "clist3");
  gtk_widget_show (clist3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), clist3);
  gtk_widget_set_size_request (clist3, 525, 275);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist3));

  label28 = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 0, label28);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_LEFT);

  label29 = gtk_label_new (_("Artist"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 1, label29);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_LEFT);

  label30 = gtk_label_new (_("Song"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 2, label30);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);

  label31 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 3, label31);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_LEFT);

  label32 = gtk_label_new (_("Ch #"));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 4, label32);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);

  label33 = gtk_label_new (_("Usage"));
  gtk_widget_set_name (label33, "label33");
  gtk_widget_show (label33);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 5, label33);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_LEFT);

  label21 = gtk_label_new (_("Session"));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label21);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);

  g_signal_connect_swapped ((gpointer) window1, "realize",
                            G_CALLBACK (on_notebook1_realize),
                            GTK_OBJECT (notebook1));
  g_signal_connect_swapped ((gpointer) window1, "realize",
                            G_CALLBACK (on_clist1_realize),
                            GTK_OBJECT (clist1));
  g_signal_connect_swapped ((gpointer) window1, "realize",
                            G_CALLBACK (on_clist2_realize),
                            GTK_OBJECT (clist2));
  g_signal_connect_swapped ((gpointer) window1, "realize",
                            G_CALLBACK (on_clist3_realize),
                            GTK_OBJECT (clist3));
  g_signal_connect_swapped ((gpointer) window1, "realize",
                            G_CALLBACK (on_clist4_realize),
                            GTK_OBJECT (clist4));
  g_signal_connect ((gpointer) window1, "realize",
                    G_CALLBACK (on_setup_realize),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_radio_id1, "activate",
                    G_CALLBACK (on_show_radio_id1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (XRConnect),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (XRDisconnect),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (XRChannelUp),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (XRChannelDown),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (XRChannelJump),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (XRChannelLast),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (XRChannelRefresh),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (XRMuteOff),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (XRMuteOn),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (XRChannelListToggle),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (XRPreferences),
                    NULL);
  g_signal_connect_swapped ((gpointer) artist_entry, "realize",
                            G_CALLBACK (on_artist_entry_realize),
                            GTK_OBJECT (artist_entry));
  g_signal_connect_swapped ((gpointer) song_entry, "realize",
                            G_CALLBACK (on_song_entry_realize),
                            GTK_OBJECT (song_entry));
  g_signal_connect_swapped ((gpointer) station_entry, "realize",
                            G_CALLBACK (on_station_entry_realize),
                            GTK_OBJECT (station_entry));
  g_signal_connect_swapped ((gpointer) category_entry, "realize",
                            G_CALLBACK (on_category_entry_realize),
                            GTK_OBJECT (category_entry));
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) host_status_image, "realize",
                            G_CALLBACK (on_host_status_image_realize),
                            GTK_OBJECT (host_status_image));
  g_signal_connect_swapped ((gpointer) host_ip_entry, "realize",
                            G_CALLBACK (on_host_ip_entry_realize),
                            GTK_OBJECT (host_ip_entry));
  g_signal_connect ((gpointer) clist1, "select_row",
                    G_CALLBACK (on_clist1_select_row),
                    NULL);
  g_signal_connect ((gpointer) clist2, "select_row",
                    G_CALLBACK (on_clist2_select_row),
                    NULL);
  g_signal_connect ((gpointer) clist4, "select_row",
                    G_CALLBACK (on_clist4_select_row),
                    NULL);
  g_signal_connect ((gpointer) clist3, "select_row",
                    G_CALLBACK (on_clist3_select_row),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window1, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window1, show_radio_id1, "show_radio_id1");
  GLADE_HOOKUP_OBJECT (window1, about1, "about1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, button12, "button12");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, artist_entry, "artist_entry");
  GLADE_HOOKUP_OBJECT (window1, song_entry, "song_entry");
  GLADE_HOOKUP_OBJECT (window1, station_entry, "station_entry");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, category_entry, "category_entry");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, button16, "button16");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, button17, "button17");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, host_status_image, "host_status_image");
  GLADE_HOOKUP_OBJECT (window1, host_ip_entry, "host_ip_entry");
  GLADE_HOOKUP_OBJECT (window1, image27, "image27");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, clist2, "clist2");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window1, clist4, "clist4");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, clist3, "clist3");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox4;
  GtkWidget *image16;
  GtkWidget *image18;
  GtkWidget *label6;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton1;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_name (dialog2, "dialog2");
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox4, TRUE, TRUE, 0);

  image16 = create_pixmap (dialog2, "banner-horiz-lion-about.xpm");
  gtk_widget_set_name (image16, "image16");
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (vbox4), image16, FALSE, FALSE, 0);

  image18 = create_pixmap (dialog2, "about.xpm");
  gtk_widget_set_name (image18, "image18");
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (vbox4), image18, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Version 0.1"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox4), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0.5, 0.49);
  gtk_misc_set_padding (GTK_MISC (label6), 0, 3);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton1, "closebutton1");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) label6, "realize",
                            G_CALLBACK (on_label6_realize),
                            GTK_OBJECT (label6));
  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog2, image16, "image16");
  GLADE_HOOKUP_OBJECT (dialog2, image18, "image18");
  GLADE_HOOKUP_OBJECT (dialog2, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton1, "closebutton1");

  return dialog2;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox3;
  GtkWidget *vbox5;
  GtkWidget *image33;
  GtkWidget *label9;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton2;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_name (dialog1, "dialog1");
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));

  dialog_vbox3 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_widget_show (dialog_vbox3);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vbox5, TRUE, TRUE, 0);

  image33 = create_pixmap (dialog1, "banner-horiz.xpm");
  gtk_widget_set_name (image33, "image33");
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (vbox5), image33, FALSE, FALSE, 0);

  label9 = gtk_label_new ("");
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox5), label9, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  dialog_action_area3 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton2, "closebutton2");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) label9, "realize",
                            G_CALLBACK (on_XR_Msg_realize),
                            GTK_OBJECT (label9));
  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog1, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dialog1, image33, "image33");
  GLADE_HOOKUP_OBJECT (dialog1, label9, "label9");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog1, closebutton2, "closebutton2");

  return dialog1;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox6;
  GtkWidget *image19;
  GtkWidget *table2;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *button14;
  GtkWidget *image20;
  GtkWidget *button15;
  GtkWidget *image21;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton1;

  dialog3 = gtk_dialog_new ();
  gtk_widget_set_name (dialog3, "dialog3");
  gtk_window_set_title (GTK_WINDOW (dialog3), _("dialog4"));

  dialog_vbox4 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_set_name (dialog_vbox4, "dialog_vbox4");
  gtk_widget_show (dialog_vbox4);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox6, TRUE, TRUE, 0);

  image19 = create_pixmap (dialog3, "banner-horiz.xpm");
  gtk_widget_set_name (image19, "image19");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (vbox6), image19, FALSE, FALSE, 0);

  table2 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox6), table2, TRUE, TRUE, 0);

  label10 = gtk_label_new (_("Station #"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label10), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label10), 7, 0);

  label11 = gtk_label_new (_("Station Name"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label11), 7, 0);

  button14 = gtk_button_new ();
  gtk_widget_set_name (button14, "button14");
  gtk_widget_show (button14);
  gtk_table_attach (GTK_TABLE (table2), button14, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image20 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image20, "image20");
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (button14), image20);

  button15 = gtk_button_new ();
  gtk_widget_set_name (button15, "button15");
  gtk_widget_show (button15);
  gtk_table_attach (GTK_TABLE (table2), button15, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image21 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image21, "image21");
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (button15), image21);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table2), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table2), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area4 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_set_name (dialog_action_area4, "dialog_action_area4");
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) entry1, "realize",
                            G_CALLBACK (on_entry1_realize),
                            GTK_OBJECT (entry1));
  g_signal_connect ((gpointer) entry1, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect_swapped ((gpointer) entry2, "realize",
                            G_CALLBACK (on_entry2_realize),
                            GTK_OBJECT (entry2));
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog3, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dialog3, image19, "image19");
  GLADE_HOOKUP_OBJECT (dialog3, table2, "table2");
  GLADE_HOOKUP_OBJECT (dialog3, label10, "label10");
  GLADE_HOOKUP_OBJECT (dialog3, label11, "label11");
  GLADE_HOOKUP_OBJECT (dialog3, button14, "button14");
  GLADE_HOOKUP_OBJECT (dialog3, image20, "image20");
  GLADE_HOOKUP_OBJECT (dialog3, button15, "button15");
  GLADE_HOOKUP_OBJECT (dialog3, image21, "image21");
  GLADE_HOOKUP_OBJECT (dialog3, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (dialog3, entry2, "entry2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog3, cancelbutton1, "cancelbutton1");

  return dialog3;
}

GtkWidget*
create_favorites (void)
{
  GtkWidget *favorites;
  GtkWidget *hbox3;
  GtkWidget *label42;
  GtkWidget *button18;
  GtkWidget *image26;
  GtkWidget *button19;
  GtkWidget *image32;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  favorites = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_name (favorites, "favorites");
  gtk_window_set_title (GTK_WINDOW (favorites), _("Favorite Artist Now Playing"));
  gtk_window_set_position (GTK_WINDOW (favorites), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (favorites), TRUE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (favorites), hbox3);

  label42 = gtk_label_new (_("Notice for \nFavorite Artist \non a specified channel"));
  gtk_widget_set_name (label42, "label42");
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox3), label42, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label42), 5, 5);

  button18 = gtk_button_new ();
  gtk_widget_set_name (button18, "button18");
  gtk_widget_show (button18);
  gtk_box_pack_start (GTK_BOX (hbox3), button18, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button18, _("Jump To Station"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button18), GTK_RELIEF_NONE);

  image26 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image26, "image26");
  gtk_widget_show (image26);
  gtk_container_add (GTK_CONTAINER (button18), image26);

  button19 = gtk_button_new ();
  gtk_widget_set_name (button19, "button19");
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (hbox3), button19, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button19, _("Skip it"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button19), GTK_RELIEF_NONE);

  image32 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image32, "image32");
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (button19), image32);

  g_signal_connect_swapped ((gpointer) favorites, "realize",
                            G_CALLBACK (on_favorites_realize),
                            GTK_OBJECT (favorites));
  g_signal_connect_swapped ((gpointer) favorites, "realize",
                            G_CALLBACK (on_entry3_realize),
                            GTK_OBJECT (label42));
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (favorites, favorites, "favorites");
  GLADE_HOOKUP_OBJECT (favorites, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (favorites, label42, "label42");
  GLADE_HOOKUP_OBJECT (favorites, button18, "button18");
  GLADE_HOOKUP_OBJECT (favorites, image26, "image26");
  GLADE_HOOKUP_OBJECT (favorites, button19, "button19");
  GLADE_HOOKUP_OBJECT (favorites, image32, "image32");
  GLADE_HOOKUP_OBJECT_NO_REF (favorites, tooltips, "tooltips");

  return favorites;
}

GtkWidget*
create_deletefavorites (void)
{
  GtkWidget *deletefavorites;
  GtkWidget *hbox4;
  GtkWidget *label43;
  GtkWidget *button20;
  GtkWidget *image30;
  GtkWidget *button21;
  GtkWidget *image31;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  deletefavorites = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_name (deletefavorites, "deletefavorites");
  gtk_window_set_title (GTK_WINDOW (deletefavorites), _("Delete Favorite Artist?"));
  gtk_window_set_position (GTK_WINDOW (deletefavorites), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (deletefavorites), TRUE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (deletefavorites), hbox4);

  label43 = gtk_label_new (_("Notice to Delete\nArtist \nfrom Favorites List"));
  gtk_widget_set_name (label43, "label43");
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox4), label43, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label43), 5, 5);

  button20 = gtk_button_new ();
  gtk_widget_set_name (button20, "button20");
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (hbox4), button20, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button20, _("Delete This Artist"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button20), GTK_RELIEF_NONE);

  image30 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image30, "image30");
  gtk_widget_show (image30);
  gtk_container_add (GTK_CONTAINER (button20), image30);

  button21 = gtk_button_new ();
  gtk_widget_set_name (button21, "button21");
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (hbox4), button21, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button21, _("Don't Delete"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button21), GTK_RELIEF_NONE);

  image31 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image31, "image31");
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (button21), image31);

  g_signal_connect_swapped ((gpointer) deletefavorites, "realize",
                            G_CALLBACK (on_deletefavorites_realize),
                            GTK_OBJECT (deletefavorites));
  g_signal_connect_swapped ((gpointer) deletefavorites, "realize",
                            G_CALLBACK (on_deletelabel_realize),
                            GTK_OBJECT (label43));
  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button20_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (deletefavorites, deletefavorites, "deletefavorites");
  GLADE_HOOKUP_OBJECT (deletefavorites, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (deletefavorites, label43, "label43");
  GLADE_HOOKUP_OBJECT (deletefavorites, button20, "button20");
  GLADE_HOOKUP_OBJECT (deletefavorites, image30, "image30");
  GLADE_HOOKUP_OBJECT (deletefavorites, button21, "button21");
  GLADE_HOOKUP_OBJECT (deletefavorites, image31, "image31");
  GLADE_HOOKUP_OBJECT_NO_REF (deletefavorites, tooltips, "tooltips");

  return deletefavorites;
}

GtkWidget*
create_preferences (void)
{
  GtkWidget *preferences;
  GtkWidget *vbox8;
  GtkWidget *menubar2;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *save1;
  GtkWidget *quit2;
  GtkWidget *image34;
  GtkWidget *table3;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *entry5;
  GtkWidget *entry4;
  GtkWidget *hseparator1;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *hbox5;
  GtkWidget *label46;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *scrolledwindow5;
  GtkWidget *clist5;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  preferences = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (preferences, "preferences");
  gtk_window_set_title (GTK_WINDOW (preferences), _("Ximba Radio Preferences"));

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (preferences), vbox8);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar2, "menubar2");
  gtk_widget_show (menubar2);
  gtk_box_pack_start (GTK_BOX (vbox8), menubar2, FALSE, FALSE, 0);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem5, "menuitem5");
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem5_menu, "menuitem5_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (save1, "save1");
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), save1);

  quit2 = gtk_image_menu_item_new_from_stock ("gtk-close", accel_group);
  gtk_widget_set_name (quit2, "quit2");
  gtk_widget_show (quit2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), quit2);

  image34 = create_pixmap (preferences, "banner-horiz-lion-about.xpm");
  gtk_widget_set_name (image34, "image34");
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (vbox8), image34, FALSE, FALSE, 0);

  table3 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox8), table3, FALSE, FALSE, 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 3);

  label44 = gtk_label_new (_("OpenXM Daemon Host"));
  gtk_widget_set_name (label44, "label44");
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table3), label44, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label44), 4, 0);

  label45 = gtk_label_new (_("Location of XMDaemon"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table3), label45, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label45), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label45), 4, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_set_name (entry5, "entry5");
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table3), entry5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry5, _("Specify a hostname or IP address where your XMDaemon will be running."), NULL);

  entry4 = gtk_entry_new ();
  gtk_widget_set_name (entry4, "entry4");
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table3), entry4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry4, _("Specify the directory where the OpenXM package is installed."), NULL);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table3), hseparator1, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 2);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Show Channel Listings"));
  gtk_widget_set_name (checkbutton1, "checkbutton1");
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table3), checkbutton1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton1, _("Set this to have the Channel Listing window be displayed at startup."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Enable Favorites Notification"));
  gtk_widget_set_name (checkbutton2, "checkbutton2");
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table3), checkbutton2, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton2, _("Set this to be notified when a favorite artist is found on any station."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton2), TRUE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table3), hbox5, 0, 2, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label46 = gtk_label_new (_("Performance  Adjustment"));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox5), label46, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label46), 14, 0);

  spinbutton1_adj = gtk_adjustment_new (0, 0, 10, 1, 1, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_set_name (spinbutton1, "spinbutton1");
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox5), spinbutton1, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton1, _("Use higher values for fast systems, lower values for slower systems."), NULL);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow5, TRUE, TRUE, 0);

  clist5 = gtk_clist_new (2);
  gtk_widget_set_name (clist5, "clist5");
  gtk_widget_show (clist5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), clist5);
  gtk_tooltips_set_tip (tooltips, clist5, _("Use this window to hide category tabs that your are not interested in seeing."), NULL);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 0, 199);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist5));

  label49 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 0, label49);
  gtk_label_set_justify (GTK_LABEL (label49), GTK_JUSTIFY_LEFT);

  label50 = gtk_label_new (_("Visible"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 1, label50);
  gtk_label_set_justify (GTK_LABEL (label50), GTK_JUSTIFY_LEFT);

  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_clist5_realize),
                            GTK_OBJECT (clist5));
  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_spinbutton1_realize),
                            GTK_OBJECT (spinbutton1));
  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_checkbutton1_realize),
                            GTK_OBJECT (checkbutton1));
  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_checkbutton2_realize),
                            GTK_OBJECT (checkbutton2));
  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_entry5_realize),
                            GTK_OBJECT (entry5));
  g_signal_connect_swapped ((gpointer) preferences, "realize",
                            G_CALLBACK (on_entry4_realize),
                            GTK_OBJECT (entry4));
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit2, "activate",
                    G_CALLBACK (on_quit2_activate),
                    NULL);
  g_signal_connect ((gpointer) clist5, "select_row",
                    G_CALLBACK (on_clist5_select_row),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (preferences, preferences, "preferences");
  GLADE_HOOKUP_OBJECT (preferences, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (preferences, menubar2, "menubar2");
  GLADE_HOOKUP_OBJECT (preferences, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (preferences, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (preferences, save1, "save1");
  GLADE_HOOKUP_OBJECT (preferences, quit2, "quit2");
  GLADE_HOOKUP_OBJECT (preferences, image34, "image34");
  GLADE_HOOKUP_OBJECT (preferences, table3, "table3");
  GLADE_HOOKUP_OBJECT (preferences, label44, "label44");
  GLADE_HOOKUP_OBJECT (preferences, label45, "label45");
  GLADE_HOOKUP_OBJECT (preferences, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (preferences, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (preferences, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (preferences, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (preferences, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (preferences, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (preferences, label46, "label46");
  GLADE_HOOKUP_OBJECT (preferences, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (preferences, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (preferences, clist5, "clist5");
  GLADE_HOOKUP_OBJECT (preferences, label49, "label49");
  GLADE_HOOKUP_OBJECT (preferences, label50, "label50");
  GLADE_HOOKUP_OBJECT_NO_REF (preferences, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (preferences), accel_group);

  return preferences;
}

GtkWidget*
create_categories (void)
{
  GtkWidget *categories;
  GtkWidget *hbox6;
  GtkWidget *ChannelState;
  GtkWidget *button24;
  GtkWidget *image37;
  GtkWidget *button22;
  GtkWidget *image35;
  GtkWidget *button23;
  GtkWidget *image36;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  categories = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_name (categories, "categories");
  gtk_window_set_title (GTK_WINDOW (categories), _("Category Visible?"));
  gtk_window_set_position (GTK_WINDOW (categories), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (categories), TRUE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (categories), hbox6);

  ChannelState = gtk_label_new (_("Channel State"));
  gtk_widget_set_name (ChannelState, "ChannelState");
  gtk_widget_show (ChannelState);
  gtk_box_pack_start (GTK_BOX (hbox6), ChannelState, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (ChannelState), 5, 5);

  button24 = gtk_button_new ();
  gtk_widget_set_name (button24, "button24");
  gtk_widget_show (button24);
  gtk_box_pack_start (GTK_BOX (hbox6), button24, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button24, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button24, _("Show Channel Tab"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button24), GTK_RELIEF_NONE);

  image37 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image37, "image37");
  gtk_widget_show (image37);
  gtk_container_add (GTK_CONTAINER (button24), image37);

  button22 = gtk_button_new ();
  gtk_widget_set_name (button22, "button22");
  gtk_widget_show (button22);
  gtk_box_pack_start (GTK_BOX (hbox6), button22, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button22, _("Hide Channel Tab"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button22), GTK_RELIEF_NONE);

  image35 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image35, "image35");
  gtk_widget_show (image35);
  gtk_container_add (GTK_CONTAINER (button22), image35);

  button23 = gtk_button_new ();
  gtk_widget_set_name (button23, "button23");
  gtk_widget_show (button23);
  gtk_box_pack_start (GTK_BOX (hbox6), button23, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button23, _("Delete from list"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button23), GTK_RELIEF_NONE);

  image36 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image36, "image36");
  gtk_widget_show (image36);
  gtk_container_add (GTK_CONTAINER (button23), image36);

  g_signal_connect_swapped ((gpointer) ChannelState, "realize",
                            G_CALLBACK (on_ChannelState_realize),
                            GTK_OBJECT (ChannelState));
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (categories, categories, "categories");
  GLADE_HOOKUP_OBJECT (categories, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (categories, ChannelState, "ChannelState");
  GLADE_HOOKUP_OBJECT (categories, button24, "button24");
  GLADE_HOOKUP_OBJECT (categories, image37, "image37");
  GLADE_HOOKUP_OBJECT (categories, button22, "button22");
  GLADE_HOOKUP_OBJECT (categories, image35, "image35");
  GLADE_HOOKUP_OBJECT (categories, button23, "button23");
  GLADE_HOOKUP_OBJECT (categories, image36, "image36");
  GLADE_HOOKUP_OBJECT_NO_REF (categories, tooltips, "tooltips");

  return categories;
}

