/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_favorites (void);
GtkWidget* create_deletefavorites (void);
