/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *quit1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *show_radio_id1;
  GtkWidget *about1;
  GtkWidget *image12;
  GtkWidget *toolbar1;
  GtkWidget *button13;
  GtkWidget *button3;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *button12;
  GtkWidget *table1;
  GtkWidget *artist_entry;
  GtkWidget *song_entry;
  GtkWidget *station_entry;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *category_entry;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *hbox2;
  GtkWidget *host_ip_entry;
  GtkWidget *host_status_image;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_window_set_title (GTK_WINDOW (window1), _("Ximba Radio"));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem1_menu, "menuitem1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem4_menu, "menuitem4_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  show_radio_id1 = gtk_menu_item_new_with_mnemonic (_("_Show Radio ID"));
  gtk_widget_set_name (show_radio_id1, "show_radio_id1");
  gtk_widget_show (show_radio_id1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), show_radio_id1);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  image12 = create_pixmap (window1, "banner.xpm");
  gtk_widget_set_name (image12, "image12");
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (vbox1), image12, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (image12), 0, 0.5);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  button13 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-apply",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button13, "button13");
  gtk_widget_show (button13);
  gtk_widget_add_accelerator (button13, "clicked", accel_group,
                              GDK_O, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button3 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-close",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-up", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button4"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_U, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-down", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button5"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_widget_add_accelerator (button5, "clicked", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button6 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-jump-to",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button6, "button6");
  gtk_widget_show (button6);
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              GDK_J, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button7 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-go-back",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_widget_add_accelerator (button7, "clicked", accel_group,
                              GDK_B, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button8 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-refresh",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);

  button9 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-yes",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button9, "button9");
  gtk_widget_show (button9);
  gtk_widget_add_accelerator (button9, "clicked", accel_group,
                              GDK_O, GDK_CONTROL_MASK | GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  button10 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-no",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button10, "button10");
  gtk_widget_show (button10);
  gtk_widget_add_accelerator (button10, "clicked", accel_group,
                              GDK_M, GDK_CONTROL_MASK | GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  button11 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-justify-fill",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button11, "button11");
  gtk_widget_show (button11);
  gtk_widget_add_accelerator (button11, "clicked", accel_group,
                              GDK_L, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  button12 = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-preferences",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (button12, "button12");
  gtk_widget_show (button12);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 10);

  artist_entry = gtk_entry_new ();
  gtk_widget_set_name (artist_entry, "artist_entry");
  gtk_widget_show (artist_entry);
  gtk_table_attach (GTK_TABLE (table1), artist_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (artist_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (artist_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (artist_entry), FALSE);

  song_entry = gtk_entry_new ();
  gtk_widget_set_name (song_entry, "song_entry");
  gtk_widget_show (song_entry);
  gtk_table_attach (GTK_TABLE (table1), song_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (song_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (song_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (song_entry), FALSE);

  station_entry = gtk_entry_new ();
  gtk_widget_set_name (station_entry, "station_entry");
  gtk_widget_show (station_entry);
  gtk_table_attach (GTK_TABLE (table1), station_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (station_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (station_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (station_entry), FALSE);

  label3 = gtk_label_new (_("Song:"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 4, 0);

  label4 = gtk_label_new (_("Station"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 4, 0);

  label5 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 4, 0);

  category_entry = gtk_entry_new ();
  gtk_widget_set_name (category_entry, "category_entry");
  gtk_widget_show (category_entry);
  gtk_table_attach (GTK_TABLE (table1), category_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (category_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (category_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (category_entry), FALSE);

  label2 = gtk_label_new (_("Artist:"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 4, 0);

  label1 = gtk_label_new (_("XM Host:"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 4, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table1), hbox2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  host_ip_entry = gtk_entry_new ();
  gtk_widget_set_name (host_ip_entry, "host_ip_entry");
  gtk_widget_show (host_ip_entry);
  gtk_box_pack_start (GTK_BOX (hbox2), host_ip_entry, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (host_ip_entry, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (host_ip_entry), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (host_ip_entry), FALSE);

  host_status_image = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (host_status_image, "host_status_image");
  gtk_widget_show (host_status_image);
  gtk_box_pack_start (GTK_BOX (hbox2), host_status_image, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (host_status_image, FALSE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, FALSE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist1 = gtk_clist_new (5);
  gtk_widget_set_name (clist1, "clist1");
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_widget_set_size_request (clist1, 525, 275);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label15 = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  label16 = gtk_label_new (_("Artist"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  label17 = gtk_label_new (_("Song"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label17);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  label18 = gtk_label_new (_("Category"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label18);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  label19 = gtk_label_new (_("Ch #"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_radio_id1, "activate",
                    G_CALLBACK (on_show_radio_id1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (XRConnect),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (XRDisconnect),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (XRChannelUp),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (XRChannelDown),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (XRChannelJump),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (XRChannelLast),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (XRChannelRefresh),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (XRMuteOff),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (XRMuteOn),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (XRChannelListToggle),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (XRPreferences),
                    NULL);
  g_signal_connect_swapped ((gpointer) artist_entry, "realize",
                            G_CALLBACK (on_artist_entry_realize),
                            GTK_OBJECT (artist_entry));
  g_signal_connect_swapped ((gpointer) song_entry, "realize",
                            G_CALLBACK (on_song_entry_realize),
                            GTK_OBJECT (song_entry));
  g_signal_connect_swapped ((gpointer) station_entry, "realize",
                            G_CALLBACK (on_station_entry_realize),
                            GTK_OBJECT (station_entry));
  g_signal_connect_swapped ((gpointer) category_entry, "realize",
                            G_CALLBACK (on_category_entry_realize),
                            GTK_OBJECT (category_entry));
  g_signal_connect_swapped ((gpointer) host_ip_entry, "realize",
                            G_CALLBACK (on_host_ip_entry_realize),
                            GTK_OBJECT (host_ip_entry));
  g_signal_connect_swapped ((gpointer) host_status_image, "realize",
                            G_CALLBACK (on_host_status_image_realize),
                            GTK_OBJECT (host_status_image));
  g_signal_connect_swapped ((gpointer) scrolledwindow1, "realize",
                            G_CALLBACK (on_scrolledwindow1_realize),
                            GTK_OBJECT (scrolledwindow1));
  g_signal_connect_swapped ((gpointer) clist1, "realize",
                            G_CALLBACK (on_clist1_realize),
                            GTK_OBJECT (clist1));
  g_signal_connect ((gpointer) clist1, "select_row",
                    G_CALLBACK (on_clist1_select_row),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window1, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window1, show_radio_id1, "show_radio_id1");
  GLADE_HOOKUP_OBJECT (window1, about1, "about1");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, button12, "button12");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, artist_entry, "artist_entry");
  GLADE_HOOKUP_OBJECT (window1, song_entry, "song_entry");
  GLADE_HOOKUP_OBJECT (window1, station_entry, "station_entry");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, category_entry, "category_entry");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, host_ip_entry, "host_ip_entry");
  GLADE_HOOKUP_OBJECT (window1, host_status_image, "host_status_image");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox4;
  GtkWidget *image16;
  GtkWidget *image18;
  GtkWidget *label6;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton1;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_name (dialog2, "dialog2");
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox4, TRUE, TRUE, 0);

  image16 = create_pixmap (dialog2, "banner.xpm");
  gtk_widget_set_name (image16, "image16");
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (vbox4), image16, FALSE, FALSE, 0);

  image18 = create_pixmap (dialog2, "about.xpm");
  gtk_widget_set_name (image18, "image18");
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (vbox4), image18, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Version 0.1"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox4), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0.5, 0.49);
  gtk_misc_set_padding (GTK_MISC (label6), 0, 3);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton1, "closebutton1");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) label6, "realize",
                            G_CALLBACK (on_label6_realize),
                            GTK_OBJECT (label6));
  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog2, image16, "image16");
  GLADE_HOOKUP_OBJECT (dialog2, image18, "image18");
  GLADE_HOOKUP_OBJECT (dialog2, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton1, "closebutton1");

  return dialog2;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox3;
  GtkWidget *vbox5;
  GtkWidget *image17;
  GtkWidget *label9;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton2;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_name (dialog1, "dialog1");
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));

  dialog_vbox3 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_widget_show (dialog_vbox3);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vbox5, TRUE, TRUE, 0);

  image17 = create_pixmap (dialog1, "banner.xpm");
  gtk_widget_set_name (image17, "image17");
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (vbox5), image17, FALSE, FALSE, 0);

  label9 = gtk_label_new ("");
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox5), label9, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  dialog_action_area3 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton2, "closebutton2");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) label9, "realize",
                            G_CALLBACK (on_XR_Msg_realize),
                            GTK_OBJECT (label9));
  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog1, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dialog1, image17, "image17");
  GLADE_HOOKUP_OBJECT (dialog1, label9, "label9");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog1, closebutton2, "closebutton2");

  return dialog1;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox6;
  GtkWidget *image19;
  GtkWidget *table2;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *button14;
  GtkWidget *image20;
  GtkWidget *button15;
  GtkWidget *image21;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton1;

  dialog3 = gtk_dialog_new ();
  gtk_widget_set_name (dialog3, "dialog3");
  gtk_window_set_title (GTK_WINDOW (dialog3), _("dialog4"));

  dialog_vbox4 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_set_name (dialog_vbox4, "dialog_vbox4");
  gtk_widget_show (dialog_vbox4);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox6, TRUE, TRUE, 0);

  image19 = create_pixmap (dialog3, "banner.xpm");
  gtk_widget_set_name (image19, "image19");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (vbox6), image19, FALSE, FALSE, 0);

  table2 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox6), table2, TRUE, TRUE, 0);

  label10 = gtk_label_new (_("Station #"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label10), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label10), 7, 0);

  label11 = gtk_label_new (_("Station Name"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label11), 7, 0);

  button14 = gtk_button_new ();
  gtk_widget_set_name (button14, "button14");
  gtk_widget_show (button14);
  gtk_table_attach (GTK_TABLE (table2), button14, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image20 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image20, "image20");
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (button14), image20);

  button15 = gtk_button_new ();
  gtk_widget_set_name (button15, "button15");
  gtk_widget_show (button15);
  gtk_table_attach (GTK_TABLE (table2), button15, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image21 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image21, "image21");
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (button15), image21);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table2), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table2), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area4 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_set_name (dialog_action_area4, "dialog_action_area4");
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) entry1, "realize",
                            G_CALLBACK (on_entry1_realize),
                            GTK_OBJECT (entry1));
  g_signal_connect ((gpointer) entry1, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect_swapped ((gpointer) entry2, "realize",
                            G_CALLBACK (on_entry2_realize),
                            GTK_OBJECT (entry2));
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog3, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dialog3, image19, "image19");
  GLADE_HOOKUP_OBJECT (dialog3, table2, "table2");
  GLADE_HOOKUP_OBJECT (dialog3, label10, "label10");
  GLADE_HOOKUP_OBJECT (dialog3, label11, "label11");
  GLADE_HOOKUP_OBJECT (dialog3, button14, "button14");
  GLADE_HOOKUP_OBJECT (dialog3, image20, "image20");
  GLADE_HOOKUP_OBJECT (dialog3, button15, "button15");
  GLADE_HOOKUP_OBJECT (dialog3, image21, "image21");
  GLADE_HOOKUP_OBJECT (dialog3, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (dialog3, entry2, "entry2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog3, cancelbutton1, "cancelbutton1");

  return dialog3;
}

